import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import QRCode from "qrcode";
import {
  MAX_FRAME_EDGE,
  decodeFrame,
  decodeImageData,
  frameSize,
  scanFrames,
  type FrameCanvas,
  type FrameContext,
  type FrameSource,
} from "@/lib/qr/decode";
import { ambiguousMessage, findAssetByCode, findAssetByRef } from "@/lib/qr/lookup";
import { buildingShortCode, needsCode, qrCodeFor } from "@/lib/qr/codes";
import { replaceServerRows } from "@/lib/local";
import { resetDbForTests } from "@/lib/local/db";
import type { Asset, Building } from "@/lib/supabase/types";

/*
  jsdom has no 2d canvas, so the QR image generated by qrcode is painted
  into an RGBA buffer the way a canvas would hold it (white background,
  black modules, a quiet zone of 4 modules) and handed to the decoder.
*/
type Raster = { data: Uint8ClampedArray; width: number; height: number };

function rasterise(text: string, scale = 8, margin = 4): Raster {
  const qr = QRCode.create(text, { errorCorrectionLevel: "M" });
  const size = qr.modules.size;
  const width = (size + margin * 2) * scale;
  const data = new Uint8ClampedArray(width * width * 4).fill(255);
  for (let row = 0; row < size; row++) {
    for (let col = 0; col < size; col++) {
      if (!qr.modules.get(row, col)) continue;
      for (let y = 0; y < scale; y++) {
        for (let x = 0; x < scale; x++) {
          const px = ((row + margin) * scale + y) * width + (col + margin) * scale + x;
          data[px * 4] = 0;
          data[px * 4 + 1] = 0;
          data[px * 4 + 2] = 0;
        }
      }
    }
  }
  return { data, width, height: width };
}

function blank(width: number, height: number): Raster {
  return { data: new Uint8ClampedArray(width * height * 4).fill(255), width, height };
}

type FakeVideo = FrameSource;

function fakeContext(frames: () => Raster): FrameContext<FakeVideo> & { draws: number; reads: number } {
  const ctx = {
    draws: 0,
    reads: 0,
    drawImage() {
      ctx.draws += 1;
    },
    getImageData() {
      ctx.reads += 1;
      return { data: frames().data };
    },
  };
  return ctx;
}

describe("lib/qr/decode", () => {
  it("decodes a QR image generated with qrcode back to the same string", () => {
    const text = "FD-1A2B3C-GF-01";
    const image = rasterise(text);
    expect(decodeImageData(image.data, image.width, image.height)).toBe(text);
  });

  it("returns null for a frame without a code and for an empty frame", () => {
    const image = blank(120, 90);
    expect(decodeImageData(image.data, image.width, image.height)).toBeNull();
    expect(decodeImageData(new Uint8ClampedArray(0), 0, 0)).toBeNull();
  });

  it("draws the video on the canvas at the frame size and decodes it", () => {
    const text = "FD-1A2B3C-1F-07";
    const image = rasterise(text);
    const video: FakeVideo = { readyState: 4, videoWidth: image.width, videoHeight: image.height };
    const canvas: FrameCanvas = { width: 0, height: 0 };
    const ctx = fakeContext(() => image);
    expect(decodeFrame(video, canvas, ctx)).toBe(text);
    expect(canvas.width).toBe(image.width);
    expect(canvas.height).toBe(image.height);
    expect(ctx.draws).toBe(1);
  });

  it("skips frames while the video has no data yet", () => {
    const image = rasterise("FD-1A2B3C-GF-02");
    const video: FakeVideo = { readyState: 1, videoWidth: image.width, videoHeight: image.height };
    const ctx = fakeContext(() => image);
    expect(decodeFrame(video, { width: 0, height: 0 }, ctx)).toBeNull();
    expect(ctx.draws).toBe(0);
  });

  it("scales large frames down to the long edge limit", () => {
    expect(frameSize(1920, 1080)).toEqual({ width: MAX_FRAME_EDGE, height: 450 });
    expect(frameSize(640, 480)).toEqual({ width: 640, height: 480 });
    expect(frameSize(720, 1280)).toEqual({ width: 450, height: MAX_FRAME_EDGE });
  });
});

describe("lib/qr/decode scanFrames", () => {
  beforeEach(() => {
    vi.useFakeTimers();
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it("reads at most 10 frames a second and stops after the first value", () => {
    const text = "FD-1A2B3C-2F-03";
    const code = rasterise(text);
    const empty = blank(code.width, code.height);
    let showCode = false;
    const video: FakeVideo = { readyState: 4, videoWidth: code.width, videoHeight: code.height };
    const ctx = fakeContext(() => (showCode ? code : empty));
    const decoded: string[] = [];

    const stop = scanFrames(video, (value) => decoded.push(value), {
      canvas: { width: 0, height: 0 },
      context: ctx,
    });

    vi.advanceTimersByTime(1000);
    expect(ctx.reads).toBeLessThanOrEqual(10);
    expect(ctx.reads).toBeGreaterThanOrEqual(9);
    expect(decoded).toEqual([]);

    showCode = true;
    vi.advanceTimersByTime(100);
    expect(decoded).toEqual([text]);

    const readsAfterDecode = ctx.reads;
    vi.advanceTimersByTime(1000);
    expect(ctx.reads).toBe(readsAfterDecode);
    stop();
  });

  it("stop ends the loop before any frame is read", () => {
    const image = rasterise("FD-1A2B3C-GF-09");
    const video: FakeVideo = { readyState: 4, videoWidth: image.width, videoHeight: image.height };
    const ctx = fakeContext(() => image);
    const decoded: string[] = [];
    const stop = scanFrames(video, (value) => decoded.push(value), {
      canvas: { width: 0, height: 0 },
      context: ctx,
    });
    stop();
    vi.advanceTimersByTime(1000);
    expect(ctx.reads).toBe(0);
    expect(decoded).toEqual([]);
  });
});

const B1 = "11111111-1111-4111-8111-111111111111";
const B2 = "22222222-2222-4222-8222-222222222222";
const A1 = "aaaaaaaa-0000-4000-8000-000000000001";
const A2 = "aaaaaaaa-0000-4000-8000-000000000002";
const A3 = "aaaaaaaa-0000-4000-8000-000000000003";
const A4 = "aaaaaaaa-0000-4000-8000-000000000004";

function building(id: string, name: string): Building {
  return {
    id,
    client_id: "cccccccc-0000-4000-8000-000000000001",
    name,
    address: null,
    postcode: null,
    adjustment_pct: 100,
    notes: null,
    active: true,
    created_at: "2026-09-13T10:00:00.000Z",
    updated_at: "2026-09-13T10:00:00.000Z",
    deleted_at: null,
  };
}

function asset(id: string, buildingId: string, ref: string, qr: string | null): Asset {
  return {
    id,
    building_id: buildingId,
    floor_id: null,
    work_type: "doors",
    ref,
    subtype: "FD30",
    location: null,
    qr_code: qr,
    cycle_months: 12,
    next_due_date: null,
    status: "active",
    spec: {},
    created_by: null,
    device_id: null,
    created_at: "2026-09-13T10:00:00.000Z",
    updated_at: "2026-09-13T10:00:00.000Z",
    deleted_at: null,
    received_at: null,
  };
}

describe("lib/qr/lookup findAssetByCode", () => {
  beforeEach(async () => {
    await resetDbForTests();
    await replaceServerRows("buildings", [building(B1, "Test House"), building(B2, "Sample Court")], { all: true });
    await replaceServerRows("assets", [asset(A1, B1, "GF-01", "FD-111111-GF-01"), asset(A3, B1, "GF-02", null)], {
      buildingId: B1,
    });
    await replaceServerRows("assets", [asset(A2, B2, "GF-01", "FD-222222-GF-01"), asset(A4, B2, "1F-01", null)], {
      buildingId: B2,
    });
  });

  it("finds a door in this building", async () => {
    const match = await findAssetByCode("FD-111111-GF-01", B1);
    expect(match.kind).toBe("here");
    if (match.kind === "here") expect(match.asset.id).toBe(A1);
  });

  it("finds a door in another downloaded building and names it", async () => {
    const match = await findAssetByCode("FD-222222-GF-01", B1);
    expect(match).toMatchObject({ kind: "elsewhere", buildingName: "Sample Court" });
    if (match.kind === "elsewhere") expect(match.asset.id).toBe(A2);
  });

  it("reports a code that is not on this phone", async () => {
    expect(await findAssetByCode("FD-333333-GF-01", B1)).toEqual({ kind: "not_found" });
    expect(await findAssetByCode("   ", B1)).toEqual({ kind: "not_found" });
  });

  it("from the building list every hit names its building", async () => {
    const match = await findAssetByCode("FD-111111-GF-01", null);
    expect(match).toMatchObject({ kind: "elsewhere", buildingName: "Test House" });
  });

  it("a scanned code is matched exactly, never by case or by door number", async () => {
    expect(await findAssetByCode("fd-111111-gf-01", B1)).toEqual({ kind: "not_found" });
    expect(await findAssetByCode("GF-01", B1)).toEqual({ kind: "not_found" });
  });
});

describe("lib/qr/lookup findAssetByRef (typed door number)", () => {
  beforeEach(async () => {
    await resetDbForTests();
    await replaceServerRows("buildings", [building(B1, "Test House"), building(B2, "Sample Court")], { all: true });
    await replaceServerRows("assets", [asset(A1, B1, "GF-01", "FD-111111-GF-01"), asset(A3, B1, "GF-02", null)], {
      buildingId: B1,
    });
    await replaceServerRows("assets", [asset(A2, B2, "GF-01", "FD-222222-GF-01"), asset(A4, B2, "1F-01", null)], {
      buildingId: B2,
    });
  });

  it("opens the door of the building on screen, case, spaces and dashes ignored", async () => {
    for (const typed of ["gf 02", "gf02", "GF-02", " Gf-02 "]) {
      const byNumber = await findAssetByRef(typed, B1);
      expect(byNumber.kind).toBe("here");
      if (byNumber.kind === "here") expect(byNumber.asset.id).toBe(A3);
    }

    // GF-01 exists in both buildings, the one on screen wins
    const shared = await findAssetByRef("GF-01", B1);
    expect(shared.kind).toBe("here");
    if (shared.kind === "here") expect(shared.asset.id).toBe(A1);
  });

  it("names another downloaded building when the number is only there", async () => {
    const match = await findAssetByRef("1F-01", B1);
    expect(match).toMatchObject({ kind: "elsewhere", buildingName: "Sample Court" });
    if (match.kind === "elsewhere") expect(match.asset.id).toBe(A4);
  });

  it("from the building list a unique number names its building, a shared one asks to open the building", async () => {
    expect(await findAssetByRef("1f-01", null)).toMatchObject({ kind: "elsewhere", buildingName: "Sample Court" });
    expect(await findAssetByRef("GF-01", null)).toEqual({ kind: "ambiguous", count: 2 });
    expect(ambiguousMessage("GF-01", 2)).toBe("GF-01 is in 2 downloaded buildings. Open the building first.");
  });

  it("reports a number that is on no downloaded building", async () => {
    expect(await findAssetByRef("9F-99", B1)).toEqual({ kind: "not_found" });
    expect(await findAssetByRef("   ", B1)).toEqual({ kind: "not_found" });
    // the full code is not a door number
    expect(await findAssetByRef("FD-111111-GF-01", B1)).toEqual({ kind: "not_found" });
  });
});

describe("lib/qr/codes", () => {
  it("builds FD, 6 characters of the building id, the ref without spaces", () => {
    expect(buildingShortCode("1a2b3c4d-5e6f-4a7b-8c9d-0e1f2a3b4c5d")).toBe("1A2B3C");
    expect(qrCodeFor("1a2b3c4d-5e6f-4a7b-8c9d-0e1f2a3b4c5d", "GF-01")).toBe("FD-1A2B3C-GF-01");
    expect(qrCodeFor("1a2b3c4d-5e6f-4a7b-8c9d-0e1f2a3b4c5d", " 2F 05 ")).toBe("FD-1A2B3C-2F05");
  });

  it("only assets without a code get one", () => {
    expect(needsCode({ qr_code: null })).toBe(true);
    expect(needsCode({ qr_code: "  " })).toBe(true);
    expect(needsCode({ qr_code: "FD-1A2B3C-GF-01" })).toBe(false);
  });

  it("a generated code decodes back from its own label image", () => {
    const code = qrCodeFor("1a2b3c4d-5e6f-4a7b-8c9d-0e1f2a3b4c5d", "GF-01");
    const image = rasterise(code);
    expect(decodeImageData(image.data, image.width, image.height)).toBe(code);
  });
});
